# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install dependencies (if any)
#RUN pip install -r requirements.txt

# Run app
CMD ["python", "app.py"]
